version: '3'
services:
  server:
    command: /bin/bash ./bin/dev.sh
    environment:
      IS_DEBUG: "TRUE"
  nginx:
    volumes:
      - ./nginx/sites-enabled-dev:/etc/nginx/sites-enabled
  db:
    ports:
      - "5432:5432"
  frontend:
    command: npm run start
    expose:
      - "3000"