version: '3.7'
services:
  server:
    command: /bin/bash ./bin/dev.sh
    environment:
      - IS_DEBUG=true
  nginx:
    volumes:
      - ./nginx/conf.d-dev/django.conf:/etc/nginx/conf.d/django.conf:ro
  db:
    ports:
      - "5432:5432"
  frontend:
    command: npm run start
    expose:
      - "3000"
